name: 'Set Maven Goals'
description: 'Exports a MVN_GOALS environment variable based on combination of input variables'
inputs:
  deploy-to-acr:
    description: True if the app deploys docker images to Azure Container Registry using Jib, otherwise false
    required: true
    default: 'false'
  deploy-to-gpr:
    description: True if the app deploys JARs to Github Package Registry using deploy, otherwise false
    required: true
    default: 'false'
outputs:
  maven-goals:
    description: 'The value of the maven goal variable'
runs:
  using: 'node20'
  main: 'dist/index.js'
